/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.illud.crimestopper.client.crimestopper.api;

import com.illud.crimestopper.client.crimestopper.model.AuthorityDocumentDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-01-16T10:41:21.873813800+05:30[Asia/Colombo]")

@Api(value = "AuthorityDocumentResource", description = "the AuthorityDocumentResource API")
public interface AuthorityDocumentResourceApi {

    @ApiOperation(value = "createAuthorityDocument", nickname = "createAuthorityDocumentUsingPOST", notes = "", response = AuthorityDocumentDTO.class, tags={ "authority-document-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AuthorityDocumentDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/authority-documents",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<AuthorityDocumentDTO> createAuthorityDocumentUsingPOST(@ApiParam(value = "authorityDocumentDTO" ,required=true )  @Valid @RequestBody AuthorityDocumentDTO authorityDocumentDTO);


    @ApiOperation(value = "deleteAuthorityDocument", nickname = "deleteAuthorityDocumentUsingDELETE", notes = "", tags={ "authority-document-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/authority-documents/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteAuthorityDocumentUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllAuthorityDocuments", nickname = "getAllAuthorityDocumentsUsingGET", notes = "", response = AuthorityDocumentDTO.class, responseContainer = "List", tags={ "authority-document-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AuthorityDocumentDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/authority-documents",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<AuthorityDocumentDTO>> getAllAuthorityDocumentsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getAuthorityDocument", nickname = "getAuthorityDocumentUsingGET", notes = "", response = AuthorityDocumentDTO.class, tags={ "authority-document-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AuthorityDocumentDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/authority-documents/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<AuthorityDocumentDTO> getAuthorityDocumentUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchAuthorityDocuments", nickname = "searchAuthorityDocumentsUsingGET", notes = "", response = AuthorityDocumentDTO.class, responseContainer = "List", tags={ "authority-document-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AuthorityDocumentDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/authority-documents",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<AuthorityDocumentDTO>> searchAuthorityDocumentsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateAuthorityDocument", nickname = "updateAuthorityDocumentUsingPUT", notes = "", response = AuthorityDocumentDTO.class, tags={ "authority-document-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AuthorityDocumentDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/authority-documents",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<AuthorityDocumentDTO> updateAuthorityDocumentUsingPUT(@ApiParam(value = "authorityDocumentDTO" ,required=true )  @Valid @RequestBody AuthorityDocumentDTO authorityDocumentDTO);

}
