/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.illud.crimestopper.client.crimestopper.api;

import com.illud.crimestopper.client.crimestopper.model.UserProfileDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-01-16T10:41:21.873813800+05:30[Asia/Colombo]")

@Api(value = "UserProfileResource", description = "the UserProfileResource API")
public interface UserProfileResourceApi {

    @ApiOperation(value = "createUserProfile", nickname = "createUserProfileUsingPOST", notes = "", response = UserProfileDTO.class, tags={ "user-profile-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UserProfileDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/user-profiles",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<UserProfileDTO> createUserProfileUsingPOST(@ApiParam(value = "userProfileDTO" ,required=true )  @Valid @RequestBody UserProfileDTO userProfileDTO);


    @ApiOperation(value = "deleteUserProfile", nickname = "deleteUserProfileUsingDELETE", notes = "", tags={ "user-profile-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/user-profiles/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteUserProfileUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllUserProfiles", nickname = "getAllUserProfilesUsingGET", notes = "", response = UserProfileDTO.class, responseContainer = "List", tags={ "user-profile-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UserProfileDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/user-profiles",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<UserProfileDTO>> getAllUserProfilesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getUserProfile", nickname = "getUserProfileUsingGET", notes = "", response = UserProfileDTO.class, tags={ "user-profile-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UserProfileDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/user-profiles/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<UserProfileDTO> getUserProfileUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchUserProfiles", nickname = "searchUserProfilesUsingGET", notes = "", response = UserProfileDTO.class, responseContainer = "List", tags={ "user-profile-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UserProfileDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/user-profiles",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<UserProfileDTO>> searchUserProfilesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateUserProfile", nickname = "updateUserProfileUsingPUT", notes = "", response = UserProfileDTO.class, tags={ "user-profile-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = UserProfileDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/user-profiles",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<UserProfileDTO> updateUserProfileUsingPUT(@ApiParam(value = "userProfileDTO" ,required=true )  @Valid @RequestBody UserProfileDTO userProfileDTO);

}
